services:
  nmap-mariadb:
    container_name: nmap-mariadb
    image: mariadb:latest
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    restart: "unless-stopped"

  nmap-parser:
    container_name: nmap-parser
    build: .
    environment:
      MARIADB_HOST: nmap-mariadb
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      nmap-mariadb:
        condition: "service_healthy"
